version: "3.7"

services:
  inventory-service:
    image: inventory:latest
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
    platform: linux/amd64
